-- +goose Up
CREATE TABLE voucher (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    crew_name TEXT,
    crew_id TEXT,
    flight_number TEXT,
    flight_date TEXT,
    aircraft_type TEXT,
    seat1 TEXT,
    seat2 TEXT,
    seat3 TEXT
);

CREATE TABLE aircraft_seat (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    aircraft_type TEXT,
    row INT,
    seats_in_row TEXT[]
);

INSERT INTO aircraft_seat(aircraft_type, row, seats_in_row)
VALUES
('ATR', 1, '["A", "C", "D", "F"]'),
('ATR', 2, '["A", "C", "D", "F"]'),
('ATR', 3, '["A", "C", "D", "F"]'),
('ATR', 4, '["A", "C", "D", "F"]'),
('ATR', 5, '["A", "C", "D", "F"]'),
('ATR', 6, '["A", "C", "D", "F"]'),
('ATR', 7, '["A", "C", "D", "F"]'),
('ATR', 8, '["A", "C", "D", "F"]'),
('ATR', 9, '["A", "C", "D", "F"]'),
('ATR', 10, '["A", "C", "D", "F"]'),
('ATR', 11, '["A", "C", "D", "F"]'),
('ATR', 12, '["A", "C", "D", "F"]'),
('ATR', 13, '["A", "C", "D", "F"]'),
('ATR', 14, '["A", "C", "D", "F"]'),
('ATR', 15, '["A", "C", "D", "F"]'),
('ATR', 16, '["A", "C", "D", "F"]'),
('ATR', 17, '["A", "C", "D", "F"]'),
('ATR', 18, '["A", "C", "D", "F"]'),
('Airbus 320', 1, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 2, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 3, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 4, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 5, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 6, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 7, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 8, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 9, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 10, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 11, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 12, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 13, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 14, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 15, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 16, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 17, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 18, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 19, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 20, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 21, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 22, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 23, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 24, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 25, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 26, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 27, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 28, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 29, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 30, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 31, '["A", "B", "C", "D", "E", "F"]'),
('Airbus 320', 32, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 1, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 2, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 3, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 4, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 5, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 6, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 7, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 8, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 9, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 10, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 11, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 12, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 13, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 14, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 15, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 16, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 17, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 18, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 19, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 20, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 21, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 22, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 23, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 24, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 25, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 26, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 27, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 28, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 29, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 30, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 31, '["A", "B", "C", "D", "E", "F"]'),
('Boeing 737 Max', 32, '["A", "B", "C", "D", "E", "F"]');

-- +goose Down
DROP TABLE voucher;
DROP TABLE aircraft_seat;